spring:
  application:
    name: "configserver"
  profiles:
    active: native

  cloud:
    config:
      server:
         native:
           search-locations: "file:/home/okan/Desktop/microservice-workpsace/config"

server:
  port: 8071